version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./back/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    container_name: backend
    command: >
      sh -c '
        uwsgi --socket :8000 --module config.wsgi
      '
    volumes:
      - ./back:/code
    # ports:
    #   - "8000:8000"
    expose: # コンテナ内で公開するポートを指定
      - '8000'
    depends_on:
      - db

  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    container_name: frontend
    command: npm run serve
    volumes:
      - ./front:/code
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.13
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./back/static:/static
    ports:
      - '80:80'
    depends_on:
      - back
